### PR TITLE
Refactor the samples

### PR DESCRIPTION
**Pull request by keedya**
Remove duplicated examples
Change the way we pass parameter to the applications and to be more consistent with other demos for nautilus

### CODE REVIEW

**Review by chennv4 — CHANGES_REQUESTED** [review]
Workshop samples should be compatible with latest SDP 1.1 release and upgrading to flink 1.10 better.
These are exposed to customers I think we need to get it reviewed by Claudio or David

**Comment by keedya** [comment]
@chennv4 this supposed to be a transition PR; customer don't have latest release yet and the plan is as we speak earlier to get this done first and upgrade to 1.9 or 1.10 next
@claudiofahey Do you want to give your input here

**Comment by keedya** [comment]
@claudiofahey , @chennv4 This PR is not for upgrading to 1.1, this PR is to clean up the app configuration

**Review by chennv4 — APPROVED** [review]
LGTM

**Pull request merged**
